---
abstract: 'Clean data so it is safe to output to JSON'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  DateTime: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  JSON: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Clean-JSON
requires:
  Acme::Damn: 0
  Data::Clone: 0
  Log::Any: 0
  SHARYANTO::String::Util: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Data-Clean-JSON
  repository: http://github.com/sharyanto/perl-Data-Clean-JSON
version: 0.09
